### ISSUE TITLE
Boards Issue

### ISSUE THREAD

**Issue by donnydinero** [le-zoo/stonks#7]
Hi there, I recently purchased this plugin and upon creating a board I get an error and am unsuccessful.

`[04:03:29] [Server thread/INFO]: iAutomatic issued server command: /stonks display board create punk HOUR 10 10
[04:03:29] [Server thread/ERROR]: null
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:?] at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:298) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:282) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1944) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
org.bukkit.command.CommandException: Unhandled exception executing command 'stonks' in plugin Stonks v1.0.7at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:833) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]at java.lang.Thread.run(Thread.java:833) [?:?]
at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1909) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:68) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
Caused by: java.lang.InternalError: java.lang.reflect.InvocationTargetExceptionat sun.font.FontManagerFactory$1.run(FontManagerFactory.java:87) ~[?:?]at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:75) ~[?:?] at java.awt.Font.getFont2D(Font.java:526) ~[?:?]at java.awt.Font$FontAccessImpl.getFont2D(Font.java:265) ~[?:?]at sun.font.FontUtilities.getFont2D(FontUtilities.java:148) ~[?:?]at sun.java2d.SunGraphics2D.checkFontInfo(SunGraphics2D.java:672) ~[?:?] at sun.java2d.SunGraphics2D.getFontInfo(SunGraphics2D.java:838) ~[?:?]at sun.java2d.pipe.GlyphListPipe.drawString(GlyphListPipe.java:46) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetExceptionat jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
at sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2932) ~[?:?]at fr.lezoo.stonks.display.board.Board.getImage(Board.java:298) ~[?:?]at fr.lezoo.stonks.display.board.Board.refreshImage(Board.java:228) ~[?:?]at fr.lezoo.stonks.display.board.Board.initializeBoard(Board.java:93) ~[?:?]at fr.lezoo.stonks.display.board.Board.<init>(Board.java:65) ~[?:?] at fr.lezoo.stonks.command.nodes.display.board.CreateTreeNode.execute(CreateTreeNode.java:89) ~[?:?]at fr.lezoo.stonks.command.objects.CommandTreeRoot.onCommand(CommandTreeRoot.java:40) ~[?:?]at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]... 23 more
at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:75) ~[?:?]at java.awt.Font.getFont2D(Font.java:526) ~[?:?]at java.awt.Font$FontAccessImpl.getFont2D(Font.java:265) ~[?:?]at sun.font.FontUtilities.getFont2D(FontUtilities.java:148) ~[?:?]at sun.java2d.SunGraphics2D.checkFontInfo(SunGraphics2D.java:672) ~[?:?]at sun.java2d.SunGraphics2D.getFontInfo(SunGraphics2D.java:838) ~[?:?]at sun.java2d.pipe.GlyphListPipe.drawString(GlyphListPipe.java:46) ~[?:?]
at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:85) ~[?:?]at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]... 23 more
at sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2932) ~[?:?]at fr.lezoo.stonks.display.board.Board.getImage(Board.java:298) ~[?:?]at fr.lezoo.stonks.display.board.Board.refreshImage(Board.java:228) ~[?:?]at fr.lezoo.stonks.display.board.Board.initializeBoard(Board.java:93) ~[?:?]at fr.lezoo.stonks.display.board.Board.<init>(Board.java:65) ~[?:?]at fr.lezoo.stonks.command.nodes.display.board.CreateTreeNode.execute(CreateTreeNode.java:89) ~[?:?]at fr.lezoo.stonks.command.objects.CommandTreeRoot.onCommand(CommandTreeRoot.java:40) ~[?:?]
at sun.font.SunFontManager.<init>(SunFontManager.java:315) ~[?:?]at sun.awt.FcFontManager.<init>(FcFontManager.java:35) ~[?:?] at sun.awt.X11FontManager.<init>(X11FontManager.java:56) ~[?:?]at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:85) ~[?:?]at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is nullat sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264) ~[?:?]at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:224) ~[?:?]at sun.awt.FontConfiguration.init(FontConfiguration.java:106) ~[?:?] at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:706) ~[?:?]at sun.font.SunFontManager$2.run(SunFontManager.java:358) ~[?:?]at sun.font.SunFontManager$2.run(SunFontManager.java:315) ~[?:?]at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:75) ~[?:?]at java.awt.Font.getFont2D(Font.java:526) ~[?:?]at java.awt.Font$FontAccessImpl.getFont2D(Font.java:265) ~[?:?]
at fr.lezoo.stonks.display.board.Board.<init>(Board.java:65) ~[?:?]at fr.lezoo.stonks.command.nodes.display.board.CreateTreeNode.execute(CreateTreeNode.java:89) ~[?:?]at fr.lezoo.stonks.command.objects.CommandTreeRoot.onCommand(CommandTreeRoot.java:40) ~[?:?]at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]... 23 more
at sun.font.FontUtilities.getFont2D(FontUtilities.java:148) ~[?:?]at sun.java2d.SunGraphics2D.checkFontInfo(SunGraphics2D.java:672) ~[?:?]at sun.java2d.SunGraphics2D.getFontInfo(SunGraphics2D.java:838) ~[?:?]at sun.java2d.pipe.GlyphListPipe.drawString(GlyphListPipe.java:46) ~[?:?]at sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2932) ~[?:?]at fr.lezoo.stonks.display.board.Board.getImage(Board.java:298) ~[?:?]at fr.lezoo.stonks.display.board.Board.refreshImage(Board.java:228) ~[?:?]at fr.lezoo.stonks.display.board.Board.initializeBoard(Board.java:93) ~[?:?]`

Would appreciate any help, thanks.

**Comment by Guillaumemartinfesta** [comment]
You changed your font right ? I think this bug comes from the fact that the font filled doesn't exist. Talk on the discord channel for the rest it is easier from me as I don't come often to Stonks github bc the plugin is broadly used yet.

**Comment by Guillaumemartinfesta** [comment]
By looking more into it, the bug might be worse than that tell me on discord if you resolved it/ have new ideas bc it doesn't come from "Minecraft" but on the code I use to draw the board that is why it might be hard to resolve.
